<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VariableConfigurable', 'doctrine');

/**
 * BaseVariableConfigurable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_variable_configurable
 * @property string $nombre
 * @property string $valor
 * 
 * @method integer              getIdVariableConfigurable()   Returns the current record's "id_variable_configurable" value
 * @method string               getNombre()                   Returns the current record's "nombre" value
 * @method string               getValor()                    Returns the current record's "valor" value
 * @method VariableConfigurable setIdVariableConfigurable()   Sets the current record's "id_variable_configurable" value
 * @method VariableConfigurable setNombre()                   Sets the current record's "nombre" value
 * @method VariableConfigurable setValor()                    Sets the current record's "valor" value
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVariableConfigurable extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('variable_configurable');
        $this->hasColumn('id_variable_configurable', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('valor', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}