<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Homologacion', 'doctrine');

/**
 * BaseHomologacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_homologacion
 * @property string $institucion_origen
 * @property string $programa_origen
 * @property float $nota_aprobatoria
 * @property integer $is_oficializado
 * @property integer $is_interna
 * @property string $observaciones
 * @property string $codigo_pensum_destino
 * @property string $codigo_pensum_origen
 * @property integer $id_usuario
 * @property integer $id_sf_guard_user
 * @property Usuario $Usuario
 * @property Pensum $PensumOrigen
 * @property Pensum $PensumDestino
 * @property Doctrine_Collection $AsignaturaHomologada
 * 
 * @method integer             getIdHomologacion()        Returns the current record's "id_homologacion" value
 * @method string              getInstitucionOrigen()     Returns the current record's "institucion_origen" value
 * @method string              getProgramaOrigen()        Returns the current record's "programa_origen" value
 * @method float               getNotaAprobatoria()       Returns the current record's "nota_aprobatoria" value
 * @method integer             getIsOficializado()        Returns the current record's "is_oficializado" value
 * @method integer             getIsInterna()             Returns the current record's "is_interna" value
 * @method string              getObservaciones()         Returns the current record's "observaciones" value
 * @method string              getCodigoPensumDestino()   Returns the current record's "codigo_pensum_destino" value
 * @method string              getCodigoPensumOrigen()    Returns the current record's "codigo_pensum_origen" value
 * @method integer             getIdUsuario()             Returns the current record's "id_usuario" value
 * @method integer             getIdSfGuardUser()         Returns the current record's "id_sf_guard_user" value
 * @method Usuario             getUsuario()               Returns the current record's "Usuario" value
 * @method Pensum              getPensumOrigen()          Returns the current record's "PensumOrigen" value
 * @method Pensum              getPensumDestino()         Returns the current record's "PensumDestino" value
 * @method Doctrine_Collection getAsignaturaHomologada()  Returns the current record's "AsignaturaHomologada" collection
 * @method Homologacion        setIdHomologacion()        Sets the current record's "id_homologacion" value
 * @method Homologacion        setInstitucionOrigen()     Sets the current record's "institucion_origen" value
 * @method Homologacion        setProgramaOrigen()        Sets the current record's "programa_origen" value
 * @method Homologacion        setNotaAprobatoria()       Sets the current record's "nota_aprobatoria" value
 * @method Homologacion        setIsOficializado()        Sets the current record's "is_oficializado" value
 * @method Homologacion        setIsInterna()             Sets the current record's "is_interna" value
 * @method Homologacion        setObservaciones()         Sets the current record's "observaciones" value
 * @method Homologacion        setCodigoPensumDestino()   Sets the current record's "codigo_pensum_destino" value
 * @method Homologacion        setCodigoPensumOrigen()    Sets the current record's "codigo_pensum_origen" value
 * @method Homologacion        setIdUsuario()             Sets the current record's "id_usuario" value
 * @method Homologacion        setIdSfGuardUser()         Sets the current record's "id_sf_guard_user" value
 * @method Homologacion        setUsuario()               Sets the current record's "Usuario" value
 * @method Homologacion        setPensumOrigen()          Sets the current record's "PensumOrigen" value
 * @method Homologacion        setPensumDestino()         Sets the current record's "PensumDestino" value
 * @method Homologacion        setAsignaturaHomologada()  Sets the current record's "AsignaturaHomologada" collection
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHomologacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('homologacion');
        $this->hasColumn('id_homologacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('institucion_origen', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('programa_origen', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('nota_aprobatoria', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('is_oficializado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_interna', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('observaciones', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('codigo_pensum_destino', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('codigo_pensum_origen', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_sf_guard_user', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'id_usuario',
             'foreign' => 'id_usuario'));

        $this->hasOne('Pensum as PensumOrigen', array(
             'local' => 'codigo_pensum_origen',
             'foreign' => 'codigo_pensum'));

        $this->hasOne('Pensum as PensumDestino', array(
             'local' => 'codigo_pensum_destino',
             'foreign' => 'codigo_pensum'));

        $this->hasMany('AsignaturaHomologada', array(
             'local' => 'id_homologacion',
             'foreign' => 'id_homologacion'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}