<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RefTipoLugar', 'doctrine');

/**
 * BaseRefTipoLugar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_ref_tipo_lugar
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $RefLugar
 * 
 * @method integer             getIdRefTipoLugar()    Returns the current record's "id_ref_tipo_lugar" value
 * @method string              getNombre()            Returns the current record's "nombre" value
 * @method string              getDescripcion()       Returns the current record's "descripcion" value
 * @method Doctrine_Collection getRefLugar()          Returns the current record's "RefLugar" collection
 * @method RefTipoLugar        setIdRefTipoLugar()    Sets the current record's "id_ref_tipo_lugar" value
 * @method RefTipoLugar        setNombre()            Sets the current record's "nombre" value
 * @method RefTipoLugar        setDescripcion()       Sets the current record's "descripcion" value
 * @method RefTipoLugar        setRefLugar()          Sets the current record's "RefLugar" collection
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefTipoLugar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_tipo_lugar');
        $this->hasColumn('id_ref_tipo_lugar', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RefLugar', array(
             'local' => 'id_ref_tipo_lugar',
             'foreign' => 'id_ref_tipo_lugar'));
    }
}