<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RefEstadoElemento', 'doctrine');

/**
 * BaseRefEstadoElemento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_ref_estado_elemento
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $RefElemento
 * 
 * @method integer             getIdRefEstadoElemento()    Returns the current record's "id_ref_estado_elemento" value
 * @method string              getNombre()                 Returns the current record's "nombre" value
 * @method string              getDescripcion()            Returns the current record's "descripcion" value
 * @method Doctrine_Collection getRefElemento()            Returns the current record's "RefElemento" collection
 * @method RefEstadoElemento   setIdRefEstadoElemento()    Sets the current record's "id_ref_estado_elemento" value
 * @method RefEstadoElemento   setNombre()                 Sets the current record's "nombre" value
 * @method RefEstadoElemento   setDescripcion()            Sets the current record's "descripcion" value
 * @method RefEstadoElemento   setRefElemento()            Sets the current record's "RefElemento" collection
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefEstadoElemento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_estado_elemento');
        $this->hasColumn('id_ref_estado_elemento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RefElemento', array(
             'local' => 'id_ref_estado_elemento',
             'foreign' => 'id_ref_estado_elemento'));
    }
}