<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoCertificacion', 'doctrine');

/**
 * BaseTipoCertificacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tipo_certificacion
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $Certificacion
 * 
 * @method integer             getIdTipoCertificacion()   Returns the current record's "id_tipo_certificacion" value
 * @method string              getNombre()                Returns the current record's "nombre" value
 * @method string              getDescripcion()           Returns the current record's "descripcion" value
 * @method Doctrine_Collection getCertificacion()         Returns the current record's "Certificacion" collection
 * @method TipoCertificacion   setIdTipoCertificacion()   Sets the current record's "id_tipo_certificacion" value
 * @method TipoCertificacion   setNombre()                Sets the current record's "nombre" value
 * @method TipoCertificacion   setDescripcion()           Sets the current record's "descripcion" value
 * @method TipoCertificacion   setCertificacion()         Sets the current record's "Certificacion" collection
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoCertificacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_certificacion');
        $this->hasColumn('id_tipo_certificacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('descripcion', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Certificacion', array(
             'local' => 'id_tipo_certificacion',
             'foreign' => 'id_tipo_certificacion'));
    }
}