<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Inscrito', 'doctrine');

/**
 * BaseInscrito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $numero_formulario
 * @property integer $id_jornada
 * @property integer $id_tipo_pago
 * @property integer $id_periodo
 * @property integer $id_usuario
 * @property integer $is_matriculado
 * @property date $fecha_inscripcion
 * @property Jornada $Jornada
 * @property PeriodoAcademico $PeriodoAcademico
 * @property TipoPago $TipoPago
 * @property Usuario $Usuario
 * 
 * @method string           getNumeroFormulario()  Returns the current record's "numero_formulario" value
 * @method integer          getIdJornada()         Returns the current record's "id_jornada" value
 * @method integer          getIdTipoPago()        Returns the current record's "id_tipo_pago" value
 * @method integer          getIdPeriodo()         Returns the current record's "id_periodo" value
 * @method integer          getIdUsuario()         Returns the current record's "id_usuario" value
 * @method integer          getIsMatriculado()     Returns the current record's "is_matriculado" value
 * @method date             getFechaInscripcion()  Returns the current record's "fecha_inscripcion" value
 * @method Jornada          getJornada()           Returns the current record's "Jornada" value
 * @method PeriodoAcademico getPeriodoAcademico()  Returns the current record's "PeriodoAcademico" value
 * @method TipoPago         getTipoPago()          Returns the current record's "TipoPago" value
 * @method Usuario          getUsuario()           Returns the current record's "Usuario" value
 * @method Inscrito         setNumeroFormulario()  Sets the current record's "numero_formulario" value
 * @method Inscrito         setIdJornada()         Sets the current record's "id_jornada" value
 * @method Inscrito         setIdTipoPago()        Sets the current record's "id_tipo_pago" value
 * @method Inscrito         setIdPeriodo()         Sets the current record's "id_periodo" value
 * @method Inscrito         setIdUsuario()         Sets the current record's "id_usuario" value
 * @method Inscrito         setIsMatriculado()     Sets the current record's "is_matriculado" value
 * @method Inscrito         setFechaInscripcion()  Sets the current record's "fecha_inscripcion" value
 * @method Inscrito         setJornada()           Sets the current record's "Jornada" value
 * @method Inscrito         setPeriodoAcademico()  Sets the current record's "PeriodoAcademico" value
 * @method Inscrito         setTipoPago()          Sets the current record's "TipoPago" value
 * @method Inscrito         setUsuario()           Sets the current record's "Usuario" value
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInscrito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inscrito');
        $this->hasColumn('numero_formulario', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('id_jornada', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo_pago', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_periodo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_matriculado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('fecha_inscripcion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Jornada', array(
             'local' => 'id_jornada',
             'foreign' => 'id_jornada'));

        $this->hasOne('PeriodoAcademico', array(
             'local' => 'id_periodo',
             'foreign' => 'id_periodo_academico'));

        $this->hasOne('TipoPago', array(
             'local' => 'id_tipo_pago',
             'foreign' => 'id_tipo_pago'));

        $this->hasOne('Usuario', array(
             'local' => 'id_usuario',
             'foreign' => 'id_usuario'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}