<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RefPrestamo', 'doctrine');

/**
 * BaseRefPrestamo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_ref_prestamo
 * @property integer $id_prestamista
 * @property integer $id_solicitante
 * @property timestamp $fecha_solicitud
 * @property timestamp $fecha_entrega
 * @property timestamp $fecha_retorno
 * @property timestamp $fecha_devolucion
 * @property string $observaciones
 * @property integer $id_ref_elemento
 * @property RefElemento $RefElemento
 * @property Usuario $Usuario
 * @property Usuario $Usuario_3
 * 
 * @method integer     getIdRefPrestamo()    Returns the current record's "id_ref_prestamo" value
 * @method integer     getIdPrestamista()    Returns the current record's "id_prestamista" value
 * @method integer     getIdSolicitante()    Returns the current record's "id_solicitante" value
 * @method timestamp   getFechaSolicitud()   Returns the current record's "fecha_solicitud" value
 * @method timestamp   getFechaEntrega()     Returns the current record's "fecha_entrega" value
 * @method timestamp   getFechaRetorno()     Returns the current record's "fecha_retorno" value
 * @method timestamp   getFechaDevolucion()  Returns the current record's "fecha_devolucion" value
 * @method string      getObservaciones()    Returns the current record's "observaciones" value
 * @method integer     getIdRefElemento()    Returns the current record's "id_ref_elemento" value
 * @method RefElemento getRefElemento()      Returns the current record's "RefElemento" value
 * @method Usuario     getUsuario()          Returns the current record's "Usuario" value
 * @method Usuario     getUsuario3()         Returns the current record's "Usuario_3" value
 * @method RefPrestamo setIdRefPrestamo()    Sets the current record's "id_ref_prestamo" value
 * @method RefPrestamo setIdPrestamista()    Sets the current record's "id_prestamista" value
 * @method RefPrestamo setIdSolicitante()    Sets the current record's "id_solicitante" value
 * @method RefPrestamo setFechaSolicitud()   Sets the current record's "fecha_solicitud" value
 * @method RefPrestamo setFechaEntrega()     Sets the current record's "fecha_entrega" value
 * @method RefPrestamo setFechaRetorno()     Sets the current record's "fecha_retorno" value
 * @method RefPrestamo setFechaDevolucion()  Sets the current record's "fecha_devolucion" value
 * @method RefPrestamo setObservaciones()    Sets the current record's "observaciones" value
 * @method RefPrestamo setIdRefElemento()    Sets the current record's "id_ref_elemento" value
 * @method RefPrestamo setRefElemento()      Sets the current record's "RefElemento" value
 * @method RefPrestamo setUsuario()          Sets the current record's "Usuario" value
 * @method RefPrestamo setUsuario3()         Sets the current record's "Usuario_3" value
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefPrestamo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_prestamo');
        $this->hasColumn('id_ref_prestamo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_prestamista', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_solicitante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_solicitud', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_entrega', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_retorno', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_devolucion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('observaciones', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('id_ref_elemento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RefElemento', array(
             'local' => 'id_ref_elemento',
             'foreign' => 'id_ref_elemento'));

        $this->hasOne('Usuario', array(
             'local' => 'id_prestamista',
             'foreign' => 'id_usuario'));

        $this->hasOne('Usuario as Usuario_3', array(
             'local' => 'id_solicitante',
             'foreign' => 'id_usuario'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}