<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstadoEstudiante', 'doctrine');

/**
 * BaseEstadoEstudiante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_estado_estudiante
 * @property string $nombre
 * @property integer $is_primario
 * @property string $descripcion
 * @property Doctrine_Collection $Estudiante
 * @property Doctrine_Collection $Estudiante_3
 * 
 * @method integer             getIdEstadoEstudiante()   Returns the current record's "id_estado_estudiante" value
 * @method string              getNombre()               Returns the current record's "nombre" value
 * @method integer             getIsPrimario()           Returns the current record's "is_primario" value
 * @method string              getDescripcion()          Returns the current record's "descripcion" value
 * @method Doctrine_Collection getEstudiante()           Returns the current record's "Estudiante" collection
 * @method Doctrine_Collection getEstudiante3()          Returns the current record's "Estudiante_3" collection
 * @method EstadoEstudiante    setIdEstadoEstudiante()   Sets the current record's "id_estado_estudiante" value
 * @method EstadoEstudiante    setNombre()               Sets the current record's "nombre" value
 * @method EstadoEstudiante    setIsPrimario()           Sets the current record's "is_primario" value
 * @method EstadoEstudiante    setDescripcion()          Sets the current record's "descripcion" value
 * @method EstadoEstudiante    setEstudiante()           Sets the current record's "Estudiante" collection
 * @method EstadoEstudiante    setEstudiante3()          Sets the current record's "Estudiante_3" collection
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadoEstudiante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado_estudiante');
        $this->hasColumn('id_estado_estudiante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('is_primario', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Estudiante', array(
             'local' => 'id_estado_estudiante',
             'foreign' => 'id_estado_secundario'));

        $this->hasMany('Estudiante as Estudiante_3', array(
             'local' => 'id_estado_estudiante',
             'foreign' => 'id_estado'));
    }
}