<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GrupoHasEstudiante', 'doctrine');

/**
 * BaseGrupoHasEstudiante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codigo_estudiante
 * @property integer $id_grupo
 * @property Estudiante $Estudiante
 * @property Grupo $Grupo
 * 
 * @method string             getCodigoEstudiante()  Returns the current record's "codigo_estudiante" value
 * @method integer            getIdGrupo()           Returns the current record's "id_grupo" value
 * @method Estudiante         getEstudiante()        Returns the current record's "Estudiante" value
 * @method Grupo              getGrupo()             Returns the current record's "Grupo" value
 * @method GrupoHasEstudiante setCodigoEstudiante()  Sets the current record's "codigo_estudiante" value
 * @method GrupoHasEstudiante setIdGrupo()           Sets the current record's "id_grupo" value
 * @method GrupoHasEstudiante setEstudiante()        Sets the current record's "Estudiante" value
 * @method GrupoHasEstudiante setGrupo()             Sets the current record's "Grupo" value
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrupoHasEstudiante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grupo_has_estudiante');
        $this->hasColumn('codigo_estudiante', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('id_grupo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estudiante', array(
             'local' => 'codigo_estudiante',
             'foreign' => 'codigo_estudiante'));

        $this->hasOne('Grupo', array(
             'local' => 'id_grupo',
             'foreign' => 'id_grupo'));
    }
}