<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RefElemento', 'doctrine');

/**
 * BaseRefElemento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_ref_elemento
 * @property string $serial
 * @property string $serial_interno
 * @property string $nombre
 * @property string $marca
 * @property string $modelo
 * @property string $descripcion
 * @property float $cantidad_sancion
 * @property string $ubicacion
 * @property integer $is_prestable
 * @property integer $id_ref_tipo_elemento
 * @property integer $id_ref_lugar
 * @property integer $id_ref_estado_elemento
 * @property integer $id_ref_tipo_sancion
 * @property integer $id_usuario_responsable
 * @property RefTipoElemento $RefTipoElemento
 * @property RefEstadoElemento $RefEstadoElemento
 * @property RefLugar $RefLugar
 * @property RefTipoSancion $RefTipoSancion
 * @property Usuario $UsuarioResponsable
 * @property Doctrine_Collection $RefHojaVida
 * @property Doctrine_Collection $UsuarioHasRefElemento
 * @property Doctrine_Collection $RefPrestamo
 * @property Doctrine_Collection $RefSancion
 * @property Doctrine_Collection $RefFotoElemento
 * @property Doctrine_Collection $RefMantenimiento
 * 
 * @method integer             getIdRefElemento()          Returns the current record's "id_ref_elemento" value
 * @method string              getSerial()                 Returns the current record's "serial" value
 * @method string              getSerialInterno()          Returns the current record's "serial_interno" value
 * @method string              getNombre()                 Returns the current record's "nombre" value
 * @method string              getMarca()                  Returns the current record's "marca" value
 * @method string              getModelo()                 Returns the current record's "modelo" value
 * @method string              getDescripcion()            Returns the current record's "descripcion" value
 * @method float               getCantidadSancion()        Returns the current record's "cantidad_sancion" value
 * @method string              getUbicacion()              Returns the current record's "ubicacion" value
 * @method integer             getIsPrestable()            Returns the current record's "is_prestable" value
 * @method integer             getIdRefTipoElemento()      Returns the current record's "id_ref_tipo_elemento" value
 * @method integer             getIdRefLugar()             Returns the current record's "id_ref_lugar" value
 * @method integer             getIdRefEstadoElemento()    Returns the current record's "id_ref_estado_elemento" value
 * @method integer             getIdRefTipoSancion()       Returns the current record's "id_ref_tipo_sancion" value
 * @method integer             getIdUsuarioResponsable()   Returns the current record's "id_usuario_responsable" value
 * @method RefTipoElemento     getRefTipoElemento()        Returns the current record's "RefTipoElemento" value
 * @method RefEstadoElemento   getRefEstadoElemento()      Returns the current record's "RefEstadoElemento" value
 * @method RefLugar            getRefLugar()               Returns the current record's "RefLugar" value
 * @method RefTipoSancion      getRefTipoSancion()         Returns the current record's "RefTipoSancion" value
 * @method Usuario             getUsuarioResponsable()     Returns the current record's "UsuarioResponsable" value
 * @method Doctrine_Collection getRefHojaVida()            Returns the current record's "RefHojaVida" collection
 * @method Doctrine_Collection getUsuarioHasRefElemento()  Returns the current record's "UsuarioHasRefElemento" collection
 * @method Doctrine_Collection getRefPrestamo()            Returns the current record's "RefPrestamo" collection
 * @method Doctrine_Collection getRefSancion()             Returns the current record's "RefSancion" collection
 * @method Doctrine_Collection getRefFotoElemento()        Returns the current record's "RefFotoElemento" collection
 * @method Doctrine_Collection getRefMantenimiento()       Returns the current record's "RefMantenimiento" collection
 * @method RefElemento         setIdRefElemento()          Sets the current record's "id_ref_elemento" value
 * @method RefElemento         setSerial()                 Sets the current record's "serial" value
 * @method RefElemento         setSerialInterno()          Sets the current record's "serial_interno" value
 * @method RefElemento         setNombre()                 Sets the current record's "nombre" value
 * @method RefElemento         setMarca()                  Sets the current record's "marca" value
 * @method RefElemento         setModelo()                 Sets the current record's "modelo" value
 * @method RefElemento         setDescripcion()            Sets the current record's "descripcion" value
 * @method RefElemento         setCantidadSancion()        Sets the current record's "cantidad_sancion" value
 * @method RefElemento         setUbicacion()              Sets the current record's "ubicacion" value
 * @method RefElemento         setIsPrestable()            Sets the current record's "is_prestable" value
 * @method RefElemento         setIdRefTipoElemento()      Sets the current record's "id_ref_tipo_elemento" value
 * @method RefElemento         setIdRefLugar()             Sets the current record's "id_ref_lugar" value
 * @method RefElemento         setIdRefEstadoElemento()    Sets the current record's "id_ref_estado_elemento" value
 * @method RefElemento         setIdRefTipoSancion()       Sets the current record's "id_ref_tipo_sancion" value
 * @method RefElemento         setIdUsuarioResponsable()   Sets the current record's "id_usuario_responsable" value
 * @method RefElemento         setRefTipoElemento()        Sets the current record's "RefTipoElemento" value
 * @method RefElemento         setRefEstadoElemento()      Sets the current record's "RefEstadoElemento" value
 * @method RefElemento         setRefLugar()               Sets the current record's "RefLugar" value
 * @method RefElemento         setRefTipoSancion()         Sets the current record's "RefTipoSancion" value
 * @method RefElemento         setUsuarioResponsable()     Sets the current record's "UsuarioResponsable" value
 * @method RefElemento         setRefHojaVida()            Sets the current record's "RefHojaVida" collection
 * @method RefElemento         setUsuarioHasRefElemento()  Sets the current record's "UsuarioHasRefElemento" collection
 * @method RefElemento         setRefPrestamo()            Sets the current record's "RefPrestamo" collection
 * @method RefElemento         setRefSancion()             Sets the current record's "RefSancion" collection
 * @method RefElemento         setRefFotoElemento()        Sets the current record's "RefFotoElemento" collection
 * @method RefElemento         setRefMantenimiento()       Sets the current record's "RefMantenimiento" collection
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefElemento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_elemento');
        $this->hasColumn('id_ref_elemento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('serial', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('serial_interno', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('marca', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('modelo', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('cantidad_sancion', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('ubicacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('is_prestable', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_ref_tipo_elemento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_ref_lugar', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_ref_estado_elemento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_ref_tipo_sancion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario_responsable', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RefTipoElemento', array(
             'local' => 'id_ref_tipo_elemento',
             'foreign' => 'id_ref_tipo_elemento'));

        $this->hasOne('RefEstadoElemento', array(
             'local' => 'id_ref_estado_elemento',
             'foreign' => 'id_ref_estado_elemento'));

        $this->hasOne('RefLugar', array(
             'local' => 'id_ref_lugar',
             'foreign' => 'id_ref_lugar'));

        $this->hasOne('RefTipoSancion', array(
             'local' => 'id_ref_tipo_sancion',
             'foreign' => 'id_ref_tipo_sancion'));

        $this->hasOne('Usuario as UsuarioResponsable', array(
             'local' => 'id_usuario_responsable',
             'foreign' => 'id_usuario'));

        $this->hasMany('RefHojaVida', array(
             'local' => 'id_ref_elemento',
             'foreign' => 'id_ref_elemento'));

        $this->hasMany('UsuarioHasRefElemento', array(
             'local' => 'id_ref_elemento',
             'foreign' => 'id_ref_elemento'));

        $this->hasMany('RefPrestamo', array(
             'local' => 'id_ref_elemento',
             'foreign' => 'id_ref_elemento'));

        $this->hasMany('RefSancion', array(
             'local' => 'id_ref_elemento',
             'foreign' => 'id_ref_elemento'));

        $this->hasMany('RefFotoElemento', array(
             'local' => 'id_ref_elemento',
             'foreign' => 'id_ref_elemento'));

        $this->hasMany('RefMantenimiento', array(
             'local' => 'id_ref_elemento',
             'foreign' => 'id_ref_elemento'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}