<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Parcial', 'doctrine');

/**
 * BaseParcial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_parcial
 * @property float $porcentaje
 * @property float $calificacion
 * @property integer $id_asignatura_cursada
 * @property integer $id_calificador
 * @property Usuario $Usuario
 * @property AsignaturaCursada $AsignaturaCursada
 * 
 * @method integer           getIdParcial()             Returns the current record's "id_parcial" value
 * @method float             getPorcentaje()            Returns the current record's "porcentaje" value
 * @method float             getCalificacion()          Returns the current record's "calificacion" value
 * @method integer           getIdAsignaturaCursada()   Returns the current record's "id_asignatura_cursada" value
 * @method integer           getIdCalificador()         Returns the current record's "id_calificador" value
 * @method Usuario           getUsuario()               Returns the current record's "Usuario" value
 * @method AsignaturaCursada getAsignaturaCursada()     Returns the current record's "AsignaturaCursada" value
 * @method Parcial           setIdParcial()             Sets the current record's "id_parcial" value
 * @method Parcial           setPorcentaje()            Sets the current record's "porcentaje" value
 * @method Parcial           setCalificacion()          Sets the current record's "calificacion" value
 * @method Parcial           setIdAsignaturaCursada()   Sets the current record's "id_asignatura_cursada" value
 * @method Parcial           setIdCalificador()         Sets the current record's "id_calificador" value
 * @method Parcial           setUsuario()               Sets the current record's "Usuario" value
 * @method Parcial           setAsignaturaCursada()     Sets the current record's "AsignaturaCursada" value
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParcial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parcial');
        $this->hasColumn('id_parcial', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('porcentaje', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('calificacion', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('id_asignatura_cursada', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_calificador', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'id_calificador',
             'foreign' => 'id_usuario'));

        $this->hasOne('AsignaturaCursada', array(
             'local' => 'id_asignatura_cursada',
             'foreign' => 'id_asignatura_cursada'));
    }
}