<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoDocumento', 'doctrine');

/**
 * BaseTipoDocumento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tipo_documento
 * @property string $nombre
 * @property Doctrine_Collection $Usuario
 * @property Doctrine_Collection $FormularioInscripcion
 * @property Doctrine_Collection $CurInscrito
 * 
 * @method integer             getIdTipoDocumento()       Returns the current record's "id_tipo_documento" value
 * @method string              getNombre()                Returns the current record's "nombre" value
 * @method Doctrine_Collection getUsuario()               Returns the current record's "Usuario" collection
 * @method Doctrine_Collection getFormularioInscripcion() Returns the current record's "FormularioInscripcion" collection
 * @method Doctrine_Collection getCurInscrito()           Returns the current record's "CurInscrito" collection
 * @method TipoDocumento       setIdTipoDocumento()       Sets the current record's "id_tipo_documento" value
 * @method TipoDocumento       setNombre()                Sets the current record's "nombre" value
 * @method TipoDocumento       setUsuario()               Sets the current record's "Usuario" collection
 * @method TipoDocumento       setFormularioInscripcion() Sets the current record's "FormularioInscripcion" collection
 * @method TipoDocumento       setCurInscrito()           Sets the current record's "CurInscrito" collection
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoDocumento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_documento');
        $this->hasColumn('id_tipo_documento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Usuario', array(
             'local' => 'id_tipo_documento',
             'foreign' => 'id_tipo_documento'));

        $this->hasMany('FormularioInscripcion', array(
             'local' => 'id_tipo_documento',
             'foreign' => 'id_tipo_documento'));

        $this->hasMany('CurInscrito', array(
             'local' => 'id_tipo_documento',
             'foreign' => 'id_tipo_documento'));
    }
}