<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LibTipoSancion', 'doctrine');

/**
 * BaseLibTipoSancion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_lib_tipo_sancion
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $LibCategoria
 * @property Doctrine_Collection $LibSancion
 * @property Doctrine_Collection $LibTipoMaterial
 * 
 * @method integer             getIdLibTipoSancion()    Returns the current record's "id_lib_tipo_sancion" value
 * @method string              getNombre()              Returns the current record's "nombre" value
 * @method string              getDescripcion()         Returns the current record's "descripcion" value
 * @method Doctrine_Collection getLibCategoria()        Returns the current record's "LibCategoria" collection
 * @method Doctrine_Collection getLibSancion()          Returns the current record's "LibSancion" collection
 * @method Doctrine_Collection getLibTipoMaterial()     Returns the current record's "LibTipoMaterial" collection
 * @method LibTipoSancion      setIdLibTipoSancion()    Sets the current record's "id_lib_tipo_sancion" value
 * @method LibTipoSancion      setNombre()              Sets the current record's "nombre" value
 * @method LibTipoSancion      setDescripcion()         Sets the current record's "descripcion" value
 * @method LibTipoSancion      setLibCategoria()        Sets the current record's "LibCategoria" collection
 * @method LibTipoSancion      setLibSancion()          Sets the current record's "LibSancion" collection
 * @method LibTipoSancion      setLibTipoMaterial()     Sets the current record's "LibTipoMaterial" collection
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLibTipoSancion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lib_tipo_sancion');
        $this->hasColumn('id_lib_tipo_sancion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('LibCategoria', array(
             'local' => 'id_lib_tipo_sancion',
             'foreign' => 'id_tipo_sancion'));

        $this->hasMany('LibSancion', array(
             'local' => 'id_lib_tipo_sancion',
             'foreign' => 'id_tipo_sancion'));

        $this->hasMany('LibTipoMaterial', array(
             'local' => 'id_lib_tipo_sancion',
             'foreign' => 'id_lib_tipo_sancion'));
    }
}