<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RefFotoElemento', 'doctrine');

/**
 * BaseRefFotoElemento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_ref_foto_elemento
 * @property string $nombre
 * @property string $path
 * @property integer $id_ref_elemento
 * @property RefElemento $RefElemento
 * 
 * @method integer         getIdRefFotoElemento()    Returns the current record's "id_ref_foto_elemento" value
 * @method string          getNombre()               Returns the current record's "nombre" value
 * @method string          getPath()                 Returns the current record's "path" value
 * @method integer         getIdRefElemento()        Returns the current record's "id_ref_elemento" value
 * @method RefElemento     getRefElemento()          Returns the current record's "RefElemento" value
 * @method RefFotoElemento setIdRefFotoElemento()    Sets the current record's "id_ref_foto_elemento" value
 * @method RefFotoElemento setNombre()               Sets the current record's "nombre" value
 * @method RefFotoElemento setPath()                 Sets the current record's "path" value
 * @method RefFotoElemento setIdRefElemento()        Sets the current record's "id_ref_elemento" value
 * @method RefFotoElemento setRefElemento()          Sets the current record's "RefElemento" value
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefFotoElemento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ref_foto_elemento');
        $this->hasColumn('id_ref_foto_elemento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('path', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('id_ref_elemento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RefElemento', array(
             'local' => 'id_ref_elemento',
             'foreign' => 'id_ref_elemento'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}