<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UsuarioHasRefElemento', 'doctrine');

/**
 * BaseUsuarioHasRefElemento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_usuario
 * @property integer $id_ref_elemento
 * @property Usuario $Usuario
 * @property RefElemento $RefElemento
 * 
 * @method integer               getIdUsuario()       Returns the current record's "id_usuario" value
 * @method integer               getIdRefElemento()   Returns the current record's "id_ref_elemento" value
 * @method Usuario               getUsuario()         Returns the current record's "Usuario" value
 * @method RefElemento           getRefElemento()     Returns the current record's "RefElemento" value
 * @method UsuarioHasRefElemento setIdUsuario()       Sets the current record's "id_usuario" value
 * @method UsuarioHasRefElemento setIdRefElemento()   Sets the current record's "id_ref_elemento" value
 * @method UsuarioHasRefElemento setUsuario()         Sets the current record's "Usuario" value
 * @method UsuarioHasRefElemento setRefElemento()     Sets the current record's "RefElemento" value
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuarioHasRefElemento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario_has_ref_elemento');
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_ref_elemento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'id_usuario',
             'foreign' => 'id_usuario'));

        $this->hasOne('RefElemento', array(
             'local' => 'id_ref_elemento',
             'foreign' => 'id_ref_elemento'));
    }
}