<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Matricula', 'doctrine');

/**
 * BaseMatricula
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_matricula
 * @property date $fecha
 * @property integer $id_periodo
 * @property integer $id_jornada
 * @property integer $id_tipo_pago
 * @property string $codigo_estudiante
 * @property Estudiante $Estudiante
 * @property Jornada $Jornada
 * @property PeriodoAcademico $PeriodoAcademico
 * @property TipoPago $TipoPago
 * 
 * @method integer          getIdMatricula()       Returns the current record's "id_matricula" value
 * @method date             getFecha()             Returns the current record's "fecha" value
 * @method integer          getIdPeriodo()         Returns the current record's "id_periodo" value
 * @method integer          getIdJornada()         Returns the current record's "id_jornada" value
 * @method integer          getIdTipoPago()        Returns the current record's "id_tipo_pago" value
 * @method string           getCodigoEstudiante()  Returns the current record's "codigo_estudiante" value
 * @method Estudiante       getEstudiante()        Returns the current record's "Estudiante" value
 * @method Jornada          getJornada()           Returns the current record's "Jornada" value
 * @method PeriodoAcademico getPeriodoAcademico()  Returns the current record's "PeriodoAcademico" value
 * @method TipoPago         getTipoPago()          Returns the current record's "TipoPago" value
 * @method Matricula        setIdMatricula()       Sets the current record's "id_matricula" value
 * @method Matricula        setFecha()             Sets the current record's "fecha" value
 * @method Matricula        setIdPeriodo()         Sets the current record's "id_periodo" value
 * @method Matricula        setIdJornada()         Sets the current record's "id_jornada" value
 * @method Matricula        setIdTipoPago()        Sets the current record's "id_tipo_pago" value
 * @method Matricula        setCodigoEstudiante()  Sets the current record's "codigo_estudiante" value
 * @method Matricula        setEstudiante()        Sets the current record's "Estudiante" value
 * @method Matricula        setJornada()           Sets the current record's "Jornada" value
 * @method Matricula        setPeriodoAcademico()  Sets the current record's "PeriodoAcademico" value
 * @method Matricula        setTipoPago()          Sets the current record's "TipoPago" value
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMatricula extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('matricula');
        $this->hasColumn('id_matricula', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_periodo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_jornada', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo_pago', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_estudiante', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estudiante', array(
             'local' => 'codigo_estudiante',
             'foreign' => 'codigo_estudiante'));

        $this->hasOne('Jornada', array(
             'local' => 'id_jornada',
             'foreign' => 'id_jornada'));

        $this->hasOne('PeriodoAcademico', array(
             'local' => 'id_periodo',
             'foreign' => 'id_periodo_academico'));

        $this->hasOne('TipoPago', array(
             'local' => 'id_tipo_pago',
             'foreign' => 'id_tipo_pago'));
    }
}