<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CurEmpresa', 'doctrine');

/**
 * BaseCurEmpresa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_cur_empresa
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $CurCurso
 * 
 * @method integer             getIdCurEmpresa()   Returns the current record's "id_cur_empresa" value
 * @method string              getNombre()         Returns the current record's "nombre" value
 * @method string              getDescripcion()    Returns the current record's "descripcion" value
 * @method Doctrine_Collection getCurCurso()       Returns the current record's "CurCurso" collection
 * @method CurEmpresa          setIdCurEmpresa()   Sets the current record's "id_cur_empresa" value
 * @method CurEmpresa          setNombre()         Sets the current record's "nombre" value
 * @method CurEmpresa          setDescripcion()    Sets the current record's "descripcion" value
 * @method CurEmpresa          setCurCurso()       Sets the current record's "CurCurso" collection
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCurEmpresa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cur_empresa');
        $this->hasColumn('id_cur_empresa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CurCurso', array(
             'local' => 'id_cur_empresa',
             'foreign' => 'id_cur_empresa'));
    }
}