<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LibCategoria', 'doctrine');

/**
 * BaseLibCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codigo_lib_categoria
 * @property string $nombre
 * @property string $descripcion
 * @property integer $dias_prestamo
 * @property float $cantidad_sancion
 * @property integer $id_tipo_sancion
 * @property LibTipoSancion $LibTipoSancion
 * @property Doctrine_Collection $LibMaterial
 * 
 * @method string              getCodigoLibCategoria()   Returns the current record's "codigo_lib_categoria" value
 * @method string              getNombre()               Returns the current record's "nombre" value
 * @method string              getDescripcion()          Returns the current record's "descripcion" value
 * @method integer             getDiasPrestamo()         Returns the current record's "dias_prestamo" value
 * @method float               getCantidadSancion()      Returns the current record's "cantidad_sancion" value
 * @method integer             getIdTipoSancion()        Returns the current record's "id_tipo_sancion" value
 * @method LibTipoSancion      getLibTipoSancion()       Returns the current record's "LibTipoSancion" value
 * @method Doctrine_Collection getLibMaterial()          Returns the current record's "LibMaterial" collection
 * @method LibCategoria        setCodigoLibCategoria()   Sets the current record's "codigo_lib_categoria" value
 * @method LibCategoria        setNombre()               Sets the current record's "nombre" value
 * @method LibCategoria        setDescripcion()          Sets the current record's "descripcion" value
 * @method LibCategoria        setDiasPrestamo()         Sets the current record's "dias_prestamo" value
 * @method LibCategoria        setCantidadSancion()      Sets the current record's "cantidad_sancion" value
 * @method LibCategoria        setIdTipoSancion()        Sets the current record's "id_tipo_sancion" value
 * @method LibCategoria        setLibTipoSancion()       Sets the current record's "LibTipoSancion" value
 * @method LibCategoria        setLibMaterial()          Sets the current record's "LibMaterial" collection
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLibCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lib_categoria');
        $this->hasColumn('codigo_lib_categoria', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('dias_prestamo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cantidad_sancion', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('id_tipo_sancion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LibTipoSancion', array(
             'local' => 'id_tipo_sancion',
             'foreign' => 'id_lib_tipo_sancion'));

        $this->hasMany('LibMaterial', array(
             'local' => 'codigo_lib_categoria',
             'foreign' => 'codigo_lib_categoria'));
    }
}