<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FormularioInscripcion', 'doctrine');

/**
 * BaseFormularioInscripcion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_formulario_inscripcion
 * @property string $numero
 * @property string $codigo
 * @property string $primer_nombre
 * @property string $segundo_nombre
 * @property string $primer_apellido
 * @property string $segundo_apellido
 * @property string $documento
 * @property integer $id_tipo_documento
 * @property string $lugar_expedicion
 * @property string $lugar_nacimiento
 * @property date $fecha_nacimiento
 * @property string $libreta_militar
 * @property string $foto_path
 * @property integer $es_trabajador
 * @property string $telefono1
 * @property string $telefono2
 * @property string $direccion
 * @property string $correo
 * @property string $conocio
 * @property integer $id_tipo_pago
 * @property string $edu_basica_ano
 * @property string $edu_basica_institucion
 * @property string $edu_basica_lugar
 * @property integer $edu_media_en_curso
 * @property string $edu_media_ano
 * @property string $edu_media_institucion
 * @property string $edu_media_titulo
 * @property string $edu_media_lugar
 * @property integer $edu_superior1_en_curso
 * @property string $edu_superior1_ano
 * @property string $edu_superior1_institucion
 * @property string $edu_superior1_titulo
 * @property string $edu_superior1_lugar
 * @property integer $edu_superior2_en_curso
 * @property string $edu_superior2_ano
 * @property string $edu_superior2_institucion
 * @property string $edu_superior2_titulo
 * @property string $edu_superior2_lugar
 * @property integer $edu_superior3_en_curso
 * @property string $edu_superior3_ano
 * @property string $edu_superior3_institucion
 * @property string $edu_superior3_titulo
 * @property string $edu_superior3_lugar
 * @property string $codigo_pensum
 * @property integer $id_periodo
 * @property integer $id_jornada
 * @property integer $is_cerrado
 * @property integer $is_inscrito
 * @property TipoDocumento $TipoDocumento
 * @property Pensum $Pensum
 * @property PeriodoAcademico $PeriodoAcademico
 * @property Jornada $Jornada
 * @property TipoPago $TipoPago
 * 
 * @method integer               getIdFormularioInscripcion()   Returns the current record's "id_formulario_inscripcion" value
 * @method string                getNumero()                    Returns the current record's "numero" value
 * @method string                getCodigo()                    Returns the current record's "codigo" value
 * @method string                getPrimerNombre()              Returns the current record's "primer_nombre" value
 * @method string                getSegundoNombre()             Returns the current record's "segundo_nombre" value
 * @method string                getPrimerApellido()            Returns the current record's "primer_apellido" value
 * @method string                getSegundoApellido()           Returns the current record's "segundo_apellido" value
 * @method string                getDocumento()                 Returns the current record's "documento" value
 * @method integer               getIdTipoDocumento()           Returns the current record's "id_tipo_documento" value
 * @method string                getLugarExpedicion()           Returns the current record's "lugar_expedicion" value
 * @method string                getLugarNacimiento()           Returns the current record's "lugar_nacimiento" value
 * @method date                  getFechaNacimiento()           Returns the current record's "fecha_nacimiento" value
 * @method string                getLibretaMilitar()            Returns the current record's "libreta_militar" value
 * @method string                getFotoPath()                  Returns the current record's "foto_path" value
 * @method integer               getEsTrabajador()              Returns the current record's "es_trabajador" value
 * @method string                getTelefono1()                 Returns the current record's "telefono1" value
 * @method string                getTelefono2()                 Returns the current record's "telefono2" value
 * @method string                getDireccion()                 Returns the current record's "direccion" value
 * @method string                getCorreo()                    Returns the current record's "correo" value
 * @method string                getConocio()                   Returns the current record's "conocio" value
 * @method integer               getIdTipoPago()                Returns the current record's "id_tipo_pago" value
 * @method string                getEduBasicaAno()              Returns the current record's "edu_basica_ano" value
 * @method string                getEduBasicaInstitucion()      Returns the current record's "edu_basica_institucion" value
 * @method string                getEduBasicaLugar()            Returns the current record's "edu_basica_lugar" value
 * @method integer               getEduMediaEnCurso()           Returns the current record's "edu_media_en_curso" value
 * @method string                getEduMediaAno()               Returns the current record's "edu_media_ano" value
 * @method string                getEduMediaInstitucion()       Returns the current record's "edu_media_institucion" value
 * @method string                getEduMediaTitulo()            Returns the current record's "edu_media_titulo" value
 * @method string                getEduMediaLugar()             Returns the current record's "edu_media_lugar" value
 * @method integer               getEduSuperior1EnCurso()       Returns the current record's "edu_superior1_en_curso" value
 * @method string                getEduSuperior1Ano()           Returns the current record's "edu_superior1_ano" value
 * @method string                getEduSuperior1Institucion()   Returns the current record's "edu_superior1_institucion" value
 * @method string                getEduSuperior1Titulo()        Returns the current record's "edu_superior1_titulo" value
 * @method string                getEduSuperior1Lugar()         Returns the current record's "edu_superior1_lugar" value
 * @method integer               getEduSuperior2EnCurso()       Returns the current record's "edu_superior2_en_curso" value
 * @method string                getEduSuperior2Ano()           Returns the current record's "edu_superior2_ano" value
 * @method string                getEduSuperior2Institucion()   Returns the current record's "edu_superior2_institucion" value
 * @method string                getEduSuperior2Titulo()        Returns the current record's "edu_superior2_titulo" value
 * @method string                getEduSuperior2Lugar()         Returns the current record's "edu_superior2_lugar" value
 * @method integer               getEduSuperior3EnCurso()       Returns the current record's "edu_superior3_en_curso" value
 * @method string                getEduSuperior3Ano()           Returns the current record's "edu_superior3_ano" value
 * @method string                getEduSuperior3Institucion()   Returns the current record's "edu_superior3_institucion" value
 * @method string                getEduSuperior3Titulo()        Returns the current record's "edu_superior3_titulo" value
 * @method string                getEduSuperior3Lugar()         Returns the current record's "edu_superior3_lugar" value
 * @method string                getCodigoPensum()              Returns the current record's "codigo_pensum" value
 * @method integer               getIdPeriodo()                 Returns the current record's "id_periodo" value
 * @method integer               getIdJornada()                 Returns the current record's "id_jornada" value
 * @method integer               getIsCerrado()                 Returns the current record's "is_cerrado" value
 * @method integer               getIsInscrito()                Returns the current record's "is_inscrito" value
 * @method TipoDocumento         getTipoDocumento()             Returns the current record's "TipoDocumento" value
 * @method Pensum                getPensum()                    Returns the current record's "Pensum" value
 * @method PeriodoAcademico      getPeriodoAcademico()          Returns the current record's "PeriodoAcademico" value
 * @method Jornada               getJornada()                   Returns the current record's "Jornada" value
 * @method TipoPago              getTipoPago()                  Returns the current record's "TipoPago" value
 * @method FormularioInscripcion setIdFormularioInscripcion()   Sets the current record's "id_formulario_inscripcion" value
 * @method FormularioInscripcion setNumero()                    Sets the current record's "numero" value
 * @method FormularioInscripcion setCodigo()                    Sets the current record's "codigo" value
 * @method FormularioInscripcion setPrimerNombre()              Sets the current record's "primer_nombre" value
 * @method FormularioInscripcion setSegundoNombre()             Sets the current record's "segundo_nombre" value
 * @method FormularioInscripcion setPrimerApellido()            Sets the current record's "primer_apellido" value
 * @method FormularioInscripcion setSegundoApellido()           Sets the current record's "segundo_apellido" value
 * @method FormularioInscripcion setDocumento()                 Sets the current record's "documento" value
 * @method FormularioInscripcion setIdTipoDocumento()           Sets the current record's "id_tipo_documento" value
 * @method FormularioInscripcion setLugarExpedicion()           Sets the current record's "lugar_expedicion" value
 * @method FormularioInscripcion setLugarNacimiento()           Sets the current record's "lugar_nacimiento" value
 * @method FormularioInscripcion setFechaNacimiento()           Sets the current record's "fecha_nacimiento" value
 * @method FormularioInscripcion setLibretaMilitar()            Sets the current record's "libreta_militar" value
 * @method FormularioInscripcion setFotoPath()                  Sets the current record's "foto_path" value
 * @method FormularioInscripcion setEsTrabajador()              Sets the current record's "es_trabajador" value
 * @method FormularioInscripcion setTelefono1()                 Sets the current record's "telefono1" value
 * @method FormularioInscripcion setTelefono2()                 Sets the current record's "telefono2" value
 * @method FormularioInscripcion setDireccion()                 Sets the current record's "direccion" value
 * @method FormularioInscripcion setCorreo()                    Sets the current record's "correo" value
 * @method FormularioInscripcion setConocio()                   Sets the current record's "conocio" value
 * @method FormularioInscripcion setIdTipoPago()                Sets the current record's "id_tipo_pago" value
 * @method FormularioInscripcion setEduBasicaAno()              Sets the current record's "edu_basica_ano" value
 * @method FormularioInscripcion setEduBasicaInstitucion()      Sets the current record's "edu_basica_institucion" value
 * @method FormularioInscripcion setEduBasicaLugar()            Sets the current record's "edu_basica_lugar" value
 * @method FormularioInscripcion setEduMediaEnCurso()           Sets the current record's "edu_media_en_curso" value
 * @method FormularioInscripcion setEduMediaAno()               Sets the current record's "edu_media_ano" value
 * @method FormularioInscripcion setEduMediaInstitucion()       Sets the current record's "edu_media_institucion" value
 * @method FormularioInscripcion setEduMediaTitulo()            Sets the current record's "edu_media_titulo" value
 * @method FormularioInscripcion setEduMediaLugar()             Sets the current record's "edu_media_lugar" value
 * @method FormularioInscripcion setEduSuperior1EnCurso()       Sets the current record's "edu_superior1_en_curso" value
 * @method FormularioInscripcion setEduSuperior1Ano()           Sets the current record's "edu_superior1_ano" value
 * @method FormularioInscripcion setEduSuperior1Institucion()   Sets the current record's "edu_superior1_institucion" value
 * @method FormularioInscripcion setEduSuperior1Titulo()        Sets the current record's "edu_superior1_titulo" value
 * @method FormularioInscripcion setEduSuperior1Lugar()         Sets the current record's "edu_superior1_lugar" value
 * @method FormularioInscripcion setEduSuperior2EnCurso()       Sets the current record's "edu_superior2_en_curso" value
 * @method FormularioInscripcion setEduSuperior2Ano()           Sets the current record's "edu_superior2_ano" value
 * @method FormularioInscripcion setEduSuperior2Institucion()   Sets the current record's "edu_superior2_institucion" value
 * @method FormularioInscripcion setEduSuperior2Titulo()        Sets the current record's "edu_superior2_titulo" value
 * @method FormularioInscripcion setEduSuperior2Lugar()         Sets the current record's "edu_superior2_lugar" value
 * @method FormularioInscripcion setEduSuperior3EnCurso()       Sets the current record's "edu_superior3_en_curso" value
 * @method FormularioInscripcion setEduSuperior3Ano()           Sets the current record's "edu_superior3_ano" value
 * @method FormularioInscripcion setEduSuperior3Institucion()   Sets the current record's "edu_superior3_institucion" value
 * @method FormularioInscripcion setEduSuperior3Titulo()        Sets the current record's "edu_superior3_titulo" value
 * @method FormularioInscripcion setEduSuperior3Lugar()         Sets the current record's "edu_superior3_lugar" value
 * @method FormularioInscripcion setCodigoPensum()              Sets the current record's "codigo_pensum" value
 * @method FormularioInscripcion setIdPeriodo()                 Sets the current record's "id_periodo" value
 * @method FormularioInscripcion setIdJornada()                 Sets the current record's "id_jornada" value
 * @method FormularioInscripcion setIsCerrado()                 Sets the current record's "is_cerrado" value
 * @method FormularioInscripcion setIsInscrito()                Sets the current record's "is_inscrito" value
 * @method FormularioInscripcion setTipoDocumento()             Sets the current record's "TipoDocumento" value
 * @method FormularioInscripcion setPensum()                    Sets the current record's "Pensum" value
 * @method FormularioInscripcion setPeriodoAcademico()          Sets the current record's "PeriodoAcademico" value
 * @method FormularioInscripcion setJornada()                   Sets the current record's "Jornada" value
 * @method FormularioInscripcion setTipoPago()                  Sets the current record's "TipoPago" value
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFormularioInscripcion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('formulario_inscripcion');
        $this->hasColumn('id_formulario_inscripcion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('numero', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('codigo', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('primer_nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('segundo_nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('primer_apellido', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('segundo_apellido', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('documento', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('id_tipo_documento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('lugar_expedicion', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('lugar_nacimiento', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('fecha_nacimiento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('libreta_militar', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('foto_path', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('es_trabajador', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('telefono1', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('telefono2', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('correo', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('conocio', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('id_tipo_pago', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('edu_basica_ano', 'string', 4, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('edu_basica_institucion', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('edu_basica_lugar', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('edu_media_en_curso', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('edu_media_ano', 'string', 4, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('edu_media_institucion', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('edu_media_titulo', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('edu_media_lugar', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('edu_superior1_en_curso', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('edu_superior1_ano', 'string', 4, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('edu_superior1_institucion', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('edu_superior1_titulo', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('edu_superior1_lugar', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('edu_superior2_en_curso', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('edu_superior2_ano', 'string', 4, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('edu_superior2_institucion', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('edu_superior2_titulo', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('edu_superior2_lugar', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('edu_superior3_en_curso', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('edu_superior3_ano', 'string', 4, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('edu_superior3_institucion', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('edu_superior3_titulo', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('edu_superior3_lugar', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('codigo_pensum', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('id_periodo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_jornada', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_cerrado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_inscrito', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoDocumento', array(
             'local' => 'id_tipo_documento',
             'foreign' => 'id_tipo_documento'));

        $this->hasOne('Pensum', array(
             'local' => 'codigo_pensum',
             'foreign' => 'codigo_pensum'));

        $this->hasOne('PeriodoAcademico', array(
             'local' => 'id_periodo',
             'foreign' => 'id_periodo_academico'));

        $this->hasOne('Jornada', array(
             'local' => 'id_jornada',
             'foreign' => 'id_jornada'));

        $this->hasOne('TipoPago', array(
             'local' => 'id_tipo_pago',
             'foreign' => 'id_tipo_pago'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}