<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Asignatura', 'doctrine');

/**
 * BaseAsignatura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codigo_asignatura
 * @property string $nombre
 * @property integer $intensidad_horaria
 * @property integer $is_practica
 * @property integer $id_semestre
 * @property Semestre $Semestre
 * @property Doctrine_Collection $AsignaturaCursada
 * @property Doctrine_Collection $Grupo
 * @property Doctrine_Collection $AsignaturaHomologada
 * 
 * @method string              getCodigoAsignatura()     Returns the current record's "codigo_asignatura" value
 * @method string              getNombre()               Returns the current record's "nombre" value
 * @method integer             getIntensidadHoraria()    Returns the current record's "intensidad_horaria" value
 * @method integer             getIsPractica()           Returns the current record's "is_practica" value
 * @method integer             getIdSemestre()           Returns the current record's "id_semestre" value
 * @method Semestre            getSemestre()             Returns the current record's "Semestre" value
 * @method Doctrine_Collection getAsignaturaCursada()    Returns the current record's "AsignaturaCursada" collection
 * @method Doctrine_Collection getGrupo()                Returns the current record's "Grupo" collection
 * @method Doctrine_Collection getAsignaturaHomologada() Returns the current record's "AsignaturaHomologada" collection
 * @method Asignatura          setCodigoAsignatura()     Sets the current record's "codigo_asignatura" value
 * @method Asignatura          setNombre()               Sets the current record's "nombre" value
 * @method Asignatura          setIntensidadHoraria()    Sets the current record's "intensidad_horaria" value
 * @method Asignatura          setIsPractica()           Sets the current record's "is_practica" value
 * @method Asignatura          setIdSemestre()           Sets the current record's "id_semestre" value
 * @method Asignatura          setSemestre()             Sets the current record's "Semestre" value
 * @method Asignatura          setAsignaturaCursada()    Sets the current record's "AsignaturaCursada" collection
 * @method Asignatura          setGrupo()                Sets the current record's "Grupo" collection
 * @method Asignatura          setAsignaturaHomologada() Sets the current record's "AsignaturaHomologada" collection
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsignatura extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asignatura');
        $this->hasColumn('codigo_asignatura', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('nombre', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('intensidad_horaria', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_practica', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_semestre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Semestre', array(
             'local' => 'id_semestre',
             'foreign' => 'id_semestre'));

        $this->hasMany('AsignaturaCursada', array(
             'local' => 'codigo_asignatura',
             'foreign' => 'codigo_asignatura'));

        $this->hasMany('Grupo', array(
             'local' => 'codigo_asignatura',
             'foreign' => 'codigo_asignatura'));

        $this->hasMany('AsignaturaHomologada', array(
             'local' => 'codigo_asignatura',
             'foreign' => 'codigo_asignatura'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}