<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoPago', 'doctrine');

/**
 * BaseTipoPago
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tipo_pago
 * @property string $nombre
 * @property Doctrine_Collection $Inscrito
 * @property Doctrine_Collection $Matricula
 * 
 * @method integer             getIdTipoPago()   Returns the current record's "id_tipo_pago" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method Doctrine_Collection getInscrito()     Returns the current record's "Inscrito" collection
 * @method Doctrine_Collection getMatricula()    Returns the current record's "Matricula" collection
 * @method TipoPago            setIdTipoPago()   Sets the current record's "id_tipo_pago" value
 * @method TipoPago            setNombre()       Sets the current record's "nombre" value
 * @method TipoPago            setInscrito()     Sets the current record's "Inscrito" collection
 * @method TipoPago            setMatricula()    Sets the current record's "Matricula" collection
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoPago extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_pago');
        $this->hasColumn('id_tipo_pago', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Inscrito', array(
             'local' => 'id_tipo_pago',
             'foreign' => 'id_tipo_pago'));

        $this->hasMany('Matricula', array(
             'local' => 'id_tipo_pago',
             'foreign' => 'id_tipo_pago'));
    }
}