<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Semestre', 'doctrine');

/**
 * BaseSemestre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_semestre
 * @property integer $numero
 * @property integer $intensidad_horaria
 * @property string $codigo_pensum
 * @property Pensum $Pensum
 * @property Doctrine_Collection $Asignatura
 * 
 * @method integer             getIdSemestre()         Returns the current record's "id_semestre" value
 * @method integer             getNumero()             Returns the current record's "numero" value
 * @method integer             getIntensidadHoraria()  Returns the current record's "intensidad_horaria" value
 * @method string              getCodigoPensum()       Returns the current record's "codigo_pensum" value
 * @method Pensum              getPensum()             Returns the current record's "Pensum" value
 * @method Doctrine_Collection getAsignatura()         Returns the current record's "Asignatura" collection
 * @method Semestre            setIdSemestre()         Sets the current record's "id_semestre" value
 * @method Semestre            setNumero()             Sets the current record's "numero" value
 * @method Semestre            setIntensidadHoraria()  Sets the current record's "intensidad_horaria" value
 * @method Semestre            setCodigoPensum()       Sets the current record's "codigo_pensum" value
 * @method Semestre            setPensum()             Sets the current record's "Pensum" value
 * @method Semestre            setAsignatura()         Sets the current record's "Asignatura" collection
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSemestre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('semestre');
        $this->hasColumn('id_semestre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('numero', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('intensidad_horaria', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_pensum', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pensum', array(
             'local' => 'codigo_pensum',
             'foreign' => 'codigo_pensum'));

        $this->hasMany('Asignatura', array(
             'local' => 'id_semestre',
             'foreign' => 'id_semestre'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}