<?php

/**
 * AsignaturaCursadaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsignaturaCursadaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsignaturaCursadaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AsignaturaCursada');
    }
}