<?php

/**
 * AsignaturaHomologadaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsignaturaHomologadaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsignaturaHomologadaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AsignaturaHomologada');
    }
}