<?php

/**
 * CertificacionDocenteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CertificacionDocenteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CertificacionDocenteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CertificacionDocente');
    }
}