<?php

/**
 * CurEmpresaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CurEmpresaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CurEmpresaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CurEmpresa');
    }
}