<?php

/**
 * CurFormularioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CurFormularioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CurFormularioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CurFormulario');
    }
}