<?php

/**
 * CurInscritoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CurInscritoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CurInscritoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CurInscrito');
    }
}