<?php

/**
 * EstudianteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstudianteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstudianteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estudiante');
    }
}