<?php

/**
 * FormularioInscripcionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormularioInscripcionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormularioInscripcionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormularioInscripcion');
    }
}