<?php

/**
 * FotoUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FotoUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FotoUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FotoUsuario');
    }
}