<?php

/**
 * GrupoHasEstudianteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GrupoHasEstudianteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GrupoHasEstudianteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GrupoHasEstudiante');
    }
}