<?php

/**
 * HomologacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HomologacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HomologacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Homologacion');
    }
}