<?php

/**
 * InscritoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InscritoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InscritoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Inscrito');
    }
}