<?php

/**
 * LibCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LibCategoria extends BaseLibCategoria
{
    function __toString(){
        return $this->codigo_lib_categoria.': '.$this->nombre;
    }

}