<?php

/**
 * LibItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LibItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LibItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LibItem');
    }
}