<?php

/**
 * LibSancionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LibSancionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LibSancionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LibSancion');
    }
}