<?php

/**
 * NotificacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotificacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotificacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Notificacion');
    }
}