<?php

/**
 * PensumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PensumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PensumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pensum');
    }
}