<?php

/**
 * ProfesorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfesorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfesorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Profesor');
    }
}