<?php

/**
 * RefElementoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefElementoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefElementoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefElemento');
    }
}