<?php

/**
 * RefLugar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sicara2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RefLugar extends BaseRefLugar
{
    function __toString(){
        return $this->nombre;
    }
    
    function getPath($path=""){
        if($this->getIdRefLugarContenedor()!=null){
            return $this->getLugarContenedor()->getPath($path)." -> ".$this->getNombre();
        }
        
        return $this->getNombre();
    }
}