<?php

/**
 * RefSancionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefSancionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefSancionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefSancion');
    }
}