<?php

/**
 * RefTipoSancionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefTipoSancionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefTipoSancionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefTipoSancion');
    }
}