<?php

/**
 * TipoSangreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoSangreTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoSangreTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoSangre');
    }
}