<?php

/**
 * TipoCertificacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoCertificacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoCertificacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoCertificacion');
    }
}