<?php

/**
 * UsuarioHasRefElementoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioHasRefElementoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioHasRefElementoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuarioHasRefElemento');
    }
}