<?php

/**
 * VariableConfigurableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VariableConfigurableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VariableConfigurableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VariableConfigurable');
    }
}