## YAML Template.
all:
  is_secure: true
  credentials: inscrito
  
index:
  is_secure: true
  credentials: inscrito_listar
  
new:
  is_secure: true
  credentials: inscrito_new
  
create:
  is_secure: true
  credentials: inscrito_new
  
edit:
  is_secure: true
  credentials: inscrito_edit
  
update:
  is_secure: true
  credentials: inscrito_edit
  
ver:
  is_secure: true
  credentials: inscrito_ver
  
matricular:
  is_secure: true
  credentials: inscrito_matricular
