<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/02/29 00:05:41
sfConfig::add(array(
  'app_is_secure' => true,
  'app_sf_guard_plugin_success_signout_url' => 'sfGuardAuth/signin',
  'app_sf_guard_plugin_success_signin_url' => 'home/index',
));
