<?php
// auto-generated by sfViewConfigHandler
// date: 2012/02/29 00:05:54
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('/pmSuperfishMenuPlugin/css/superfish.css', '', array ());
  $response->addStylesheet('/pmSuperfishMenuPlugin/css/superfish-vertical.css', '', array ());
  $response->addStylesheet('/js/jquery-ui-1.8.16.custom/css/ui-lightness/jquery-ui-1.8.16.custom.css', '', array ());
  $response->addStylesheet('/js/formValidator2.5/css/validationEngine.jquery.css', '', array ());
  $response->addStylesheet('/js/DataTables-1.9.0/media/css/jquery.dataTables.css', '', array ());
  $response->addStylesheet('datatables.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addJavascript('/js/jquery-1.7.1.js', '', array ());
  $response->addJavascript('/pmSuperfishMenuPlugin/js/hoverIntent.js', '', array ());
  $response->addJavascript('/pmSuperfishMenuPlugin/js/superfish.js', '', array ());
  $response->addJavascript('/js/jquery-ui-1.8.16.custom/js/jquery-ui-1.8.16.custom.min.js', '', array ());
  $response->addJavascript('/js/formValidator2.5/js/jquery.validationEngine.js', '', array ());
  $response->addJavascript('/js/formValidator2.5/js/languages/jquery.validationEngine-es.js', '', array ());
  $response->addJavascript('/js/DataTables-1.9.0/media/js/jquery.dataTables.min.js', '', array ());


