<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/29 00:05:42

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sicara2',
  'username' => 'root',
  'password' => '123456',
  'name' => 'doctrine',
)),);
