<?php

/**
 * AsignaturaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsignaturaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsignaturaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Asignatura');
    }
}