<?php

/**
 * CertificacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CertificacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CertificacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Certificacion');
    }
}