<?php

/**
 * CurCursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CurCursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CurCursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CurCurso');
    }
}