<?php

/**
 * EstadoEstudianteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoEstudianteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoEstudianteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoEstudiante');
    }
}