<?php

/**
 * LibEstadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LibEstadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LibEstadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LibEstado');
    }
}