<?php

/**
 * LibMaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LibMaterialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LibMaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LibMaterial');
    }
}