<?php

/**
 * LibTipoSancionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LibTipoSancionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LibTipoSancionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LibTipoSancion');
    }
}