<?php

/**
 * MatriculaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MatriculaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MatriculaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Matricula');
    }
}