<?php

/**
 * ParcialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParcialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParcialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Parcial');
    }
}