<?php

/**
 * PensumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PensumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PensumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pensum');
    }
    
    public function getInscribibles(){
        $result = Doctrine_Core::getTable('Pensum')
                ->createQuery('p')
                ->where('is_inscribible = ?','1')
                ->execute();
        
        return $result;
    }
}