<?php

/**
 * PeriodoAcademicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeriodoAcademicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PeriodoAcademicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PeriodoAcademico');
    }
    
    public function getInscribibles(){
        $result = Doctrine_Core::getTable('PeriodoAcademico')
                ->createQuery('p')
                ->where('is_inscribible = ?','1')
                ->andWhere('estado != 2')
                ->execute();
        
        return $result;
    }
}