<?php

/**
 * RefFotoElementoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefFotoElementoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefFotoElementoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefFotoElemento');
    }
}