<?php

/**
 * RefLugarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefLugarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefLugarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefLugar');
    }
}