<?php

/**
 * RefMantenimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefMantenimientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefMantenimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefMantenimiento');
    }
}