<?php

/**
 * RefPrestamoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefPrestamoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefPrestamoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefPrestamo');
    }
}