<?php

/**
 * RefTipoLugarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefTipoLugarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefTipoLugarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefTipoLugar');
    }
}