<?php

/**
 * RefTipoElementoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefTipoElementoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefTipoElementoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefTipoElemento');
    }
}