<?php

/**
 * TipoPagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoPagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoPagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoPago');
    }
}